# **1.Read the data**

In [1]:
import pandas as pd
import numpy as np
#define a function to import csv

def import_csv(csvFile): #argument - pass a string
    df = pd.read_csv(csvFile)
    return df

#import 12 datasets provided
train_full_raw = import_csv("train_full.csv") 
train_count_raw = import_csv("train_count.csv")
train_tfidf_raw = import_csv("train_tfidf.csv")


dev_full_raw = import_csv("dev_full.csv")
dev_count_raw = import_csv("dev_count.csv")
dev_tfidf_raw = import_csv("dev_tfidf.csv")


test_full_raw = import_csv("test_full.csv")
test_count_raw = import_csv("test_count.csv")
test_tfidf_raw = import_csv("test_tfidf.csv")

### 1.1 Extract Features and Labels

In [2]:
#train and dev labels - "region" column
train_labels = train_full_raw['region']
dev_labels = dev_full_raw['region']

#data features - "tweet" column
train_full = train_full_raw['tweet']
train_count = train_count_raw['tweet']
train_tfidf = train_tfidf_raw['tweet']


dev_full = dev_full_raw['tweet']
dev_count = dev_count_raw['tweet']
dev_tfidf = dev_tfidf_raw['tweet']


test_full = test_full_raw['tweet']
test_count = test_count_raw['tweet']
test_tfidf = test_tfidf_raw['tweet']


### 1.2 read "vocab.txt" File

In [3]:
#import "vocab.tex" to build a vocab dictionary
#purpose: to be able to trace back for the original 'word' using 'word code'

vocab_dict = {}
vocab = open("vocab.txt", encoding="utf8") #"r" - read line by line 
vocab_lines = vocab.readlines()

for line in vocab_lines:
    value, key = line.replace("\n", "").split("\t")
    vocab_dict[int(key)] = value
#print(vocab_dict)
#print(len(vocab_dict))

### 1.3 build vector for each of the imported dataset

In [4]:
import re

def vector_transform (dataset): 
    result = []
    for line in dataset:
        line_cleaned = re.findall(r'[(](.*?)[)]', line) # ['1111, 1.0', '1875, 1.0']
        aux_line = [0 for i in range(len(vocab_dict))] #build an list of '0's with lenth of 2038
        for elm in line_cleaned:
            inx, value = elm.split(",")
            aux_line[int(inx)] = float(value)
        result.append(aux_line)
    return result

def vector_transform_glove300(glove300):
    output = []
    for item in glove300:
        lst = item.split(" ")
        aux_line = []
        for elm in lst:
            aux_line.append(float(elm))
        output.append(aux_line)
    return output

### 1.4 Transform dataset

In [5]:
#train
train_count_vector = vector_transform(train_count) 
train_tfidf_vector = vector_transform(train_tfidf)

In [6]:
#dev
dev_count_vector = vector_transform(dev_count)
dev_tfidf_vector = vector_transform(dev_tfidf)

In [7]:
#test
test_count_vector = vector_transform(test_count)
test_tfidf_vector = vector_transform(test_tfidf)

In [8]:
#train dataframes
df_tfidf = pd.DataFrame(train_tfidf_vector)
df_count = pd.DataFrame(train_count_vector)

In [9]:
#dev dataframes
dev_tfidf = pd.DataFrame(dev_tfidf_vector)
dev_tfidf 

0     1     2     3     4     5     6     7     8     9     ...  2028  \
0       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
11470   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
11471   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
11472   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
11473   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
11474   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

       2029  2030  2031  2032  2033  2034  2035  2036  2037  
0       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
11470   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
11471   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
11472   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
11473   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
11474   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[11475 rows x 2038 columns]

# **2. Zero-R Baseline**

In [10]:
from collections import Counter

majority_class = []
zero_r_predictions = []

t_labels = train_labels.values.tolist()

majority_class = max(set(t_labels), key=t_labels.count)

zero_r_predictions = [majority_class for i in range(len(dev_labels))]

print(f"The marority class is: {majority_class}")

The marority class is: NORTHEAST


# **3. Naive Bayes Classifiers**

In [11]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

def nb_Gaussian (x_train, y_train):
    
    gb = GaussianNB()
    gb.fit(x_train, y_train)
    
    return gb

def nb_Bernoulli (x_train, y_train):
    
    bnb = BernoulliNB()
    bnb.fit(x_train, y_train)
    
    return bnb

def nb_multinomial (x_train, y_train):
    
    mb = MultinomialNB()
    mb.fit(x_train, y_train)
    
    return mb

### 3.1 Implementing the Naive Bayes Classifiers 

In [12]:
#GaussianNB - build models
gb_model_count = nb_Gaussian(train_count_vector, train_labels)
gb_model_tfidf = nb_Gaussian(train_tfidf_vector, train_labels)

In [14]:
#predictions - GaussianNB
predictions_count_dev_gb = gb_model_count.predict(dev_count_vector)
predictions_tfidf_dev_gb = gb_model_tfidf.predict(dev_tfidf_vector)

In [15]:
#BernoulliNB - build models
bnb_model_count = nb_Bernoulli(train_count_vector, train_labels)
bnb_model_tfidf = nb_Bernoulli(train_tfidf_vector, train_labels)

In [16]:
#predictions - BernoulliNB
predictions_count_dev_bnb = bnb_model_count.predict(dev_count_vector)
predictions_tfidf_dev_bnb = bnb_model_tfidf.predict(dev_tfidf_vector)


In [17]:
#MultinomialNB - build models
mb_model_count = nb_multinomial(train_count_vector, train_labels)
mb_model_tfidf = nb_multinomial(train_tfidf_vector, train_labels) 
#cannot apply to glove300 as it contains negative numbers


In [18]:
#predictions - MultinomialNB
predictions_count_dev_mb = mb_model_count.predict(dev_count_vector)
predictions_tfidf_dev_mb = mb_model_tfidf.predict(dev_tfidf_vector)


In [23]:
from sklearn import metrics
#confusion matrix mnb count
print(metrics.classification_report(dev_labels, predictions_count_dev_mb))
print(metrics.confusion_matrix(dev_labels, predictions_count_dev_mb))
#confusion matrix mnb tfidf
print(metrics.classification_report(dev_labels,predictions_tfidf_dev_mb))
print(metrics.confusion_matrix(dev_labels,predictions_tfidf_dev_mb))

              precision    recall  f1-score   support

     MIDWEST       0.21      0.03      0.06      1484
   NORTHEAST       0.51      0.61      0.56      4295
       SOUTH       0.43      0.58      0.49      4266
        WEST       0.18      0.05      0.08      1430

    accuracy                           0.45     11475
   macro avg       0.33      0.32      0.30     11475
weighted avg       0.40      0.45      0.41     11475

[[  47  475  917   45]
 [  62 2621 1518   94]
 [  82 1497 2466  221]
 [  32  509  812   77]]
              precision    recall  f1-score   support

     MIDWEST       0.00      0.00      0.00      1484
   NORTHEAST       0.50      0.62      0.56      4295
       SOUTH       0.43      0.62      0.51      4266
        WEST       0.28      0.01      0.01      1430

    accuracy                           0.46     11475
   macro avg       0.30      0.31      0.27     11475
weighted avg       0.38      0.46      0.40     11475

[[   0  496  987    1]
 [   0 2683 16

In [28]:
#confusion matrix bnb count
print(metrics.classification_report(dev_labels, predictions_count_dev_bnb))

#confusion matrix bnb tfidf
print(metrics.classification_report(dev_labels,predictions_tfidf_dev_bnb))

              precision    recall  f1-score   support

     MIDWEST       0.21      0.03      0.05      1484
   NORTHEAST       0.51      0.62      0.56      4295
       SOUTH       0.43      0.58      0.50      4266
        WEST       0.19      0.05      0.07      1430

    accuracy                           0.46     11475
   macro avg       0.33      0.32      0.29     11475
weighted avg       0.40      0.46      0.41     11475

              precision    recall  f1-score   support

     MIDWEST       0.21      0.03      0.05      1484
   NORTHEAST       0.51      0.62      0.56      4295
       SOUTH       0.43      0.58      0.50      4266
        WEST       0.19      0.05      0.07      1430

    accuracy                           0.46     11475
   macro avg       0.33      0.32      0.29     11475
weighted avg       0.40      0.46      0.41     11475



# **4. Logistic Regression**

In [24]:
from sklearn.linear_model import LogisticRegression
def logisticR (x_train, y_train):
    
    lr = LogisticRegression(penalty='l2', max_iter = 300, multi_class = 'multinomial')
    lr.fit(x_train, y_train)
    
    return lr

In [25]:
#build model - count
lr_count_model = logisticR (train_count_vector, train_labels)

#make predictions - count
predictions_count_dev_lr = lr_count_model.predict(dev_count_vector)

c:\users\tuohuang\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [26]:
#build model - tfidf
lr_tfidf_model = logisticR (train_count_vector, train_labels)
#make predictions - tfidf
predictions_tfidf_dev_lr = lr_tfidf_model.predict(dev_tfidf_vector)

c:\users\tuohuang\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [27]:
#confusion matrix LR count
print(metrics.classification_report(dev_labels, predictions_count_dev_lr))

#confusion matrix LR tfidf
print(metrics.classification_report(dev_labels,predictions_tfidf_dev_lr))


              precision    recall  f1-score   support

     MIDWEST       0.24      0.02      0.03      1484
   NORTHEAST       0.50      0.63      0.56      4295
       SOUTH       0.43      0.58      0.50      4266
        WEST       0.20      0.03      0.05      1430

    accuracy                           0.46     11475
   macro avg       0.34      0.31      0.28     11475
weighted avg       0.40      0.46      0.40     11475

              precision    recall  f1-score   support

     MIDWEST       0.00      0.00      0.00      1484
   NORTHEAST       0.45      0.73      0.56      4295
       SOUTH       0.44      0.45      0.44      4266
        WEST       0.56      0.00      0.01      1430

    accuracy                           0.44     11475
   macro avg       0.36      0.30      0.25     11475
weighted avg       0.40      0.44      0.37     11475



# **5. SVM**

In [29]:
from sklearn import svm
import matplotlib.pyplot as plt

#Linear SVC
def lin_svm_clf (x_train, y_train):
    lin_clf = svm.LinearSVC()
    lin_clf.fit(x_train, y_train)
  
    return lin_clf

In [30]:
#build models - count
svm_count_model = lin_svm_clf(train_count_vector, train_labels)
#make predictions -count
predictions_count_dev_svm = svm_count_model.predict(dev_count_vector)

c:\users\tuohuang\appdata\local\programs\python\python39\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [31]:
#build models - tfidf
svm_tfidf_model = lin_svm_clf(train_tfidf_vector, train_labels)
#make predictions - tfidf
predictions_tfidf_dev_svm = svm_tfidf_model.predict(dev_tfidf_vector)

In [32]:
#confusion matrix LR count
print(metrics.classification_report(dev_labels, predictions_count_dev_svm))

#confusion matrix LR tfidf
print(metrics.classification_report(dev_labels,predictions_tfidf_dev_svm))

              precision    recall  f1-score   support

     MIDWEST       0.24      0.00      0.01      1484
   NORTHEAST       0.49      0.65      0.56      4295
       SOUTH       0.44      0.58      0.50      4266
        WEST       0.22      0.03      0.05      1430

    accuracy                           0.46     11475
   macro avg       0.35      0.31      0.28     11475
weighted avg       0.40      0.46      0.40     11475

              precision    recall  f1-score   support

     MIDWEST       0.18      0.00      0.00      1484
   NORTHEAST       0.50      0.63      0.55      4295
       SOUTH       0.43      0.60      0.50      4266
        WEST       0.26      0.03      0.05      1430

    accuracy                           0.46     11475
   macro avg       0.34      0.31      0.28     11475
weighted avg       0.40      0.46      0.40     11475



# 6.SGD

In [33]:
#SVC SVM
from sklearn.linear_model import SGDClassifier

def SGD_svm (x_train, y_train):
    
    stochastic_SVM = SGDClassifier(loss='hinge', shuffle=True, random_state=101, alpha=0.0001, l1_ratio=0.15)
    stochastic_SVM.fit(x_train, y_train)
  
    return stochastic_SVM

In [34]:
#SVC COUNT
svm_count_SGD = SGD_svm(train_count_vector, train_labels)
predictions_count_dev_SGD = svm_count_SGD.predict(dev_count_vector)

In [35]:
#SVC TF-IDF
svm_tfidf_SGD = SGD_svm(train_tfidf_vector, train_labels)
predictions_tfidf_dev_SGD = svm_tfidf_SGD.predict(dev_tfidf_vector)

# **7. Evaluation**

In [40]:
from sklearn import metrics
from sklearn.metrics import f1_score

def accurate(labels_observed, labels_predicted):
    accuracy = 0
    accuracy = metrics.accuracy_score(labels_observed, labels_predicted)
    return accuracy

In [43]:
#Zero-R
zero_r_acc = accurate(dev_labels, zero_r_predictions)
zero_r_f1 = f1_score(dev_labels, zero_r_predictions, average='macro')

#GaussianNB on COUNT
gb_count_acc = accurate(dev_labels, predictions_count_dev_gb)
gb_count_f1 = f1_score(dev_labels, predictions_count_dev_gb, average='macro')

#BernoulliNB on COUNT
bnb_count_acc = accurate(dev_labels, predictions_count_dev_bnb)
bnb_count_f1 = f1_score(dev_labels, predictions_count_dev_bnb, average='macro')

#MultinomialNB on count
mb_count_acc = accurate(dev_labels, predictions_count_dev_mb)
mb_count_f1 = f1_score(dev_labels, predictions_count_dev_mb, average='macro')

#GaussianNB on TFIDF
gb_tfidf_acc = accurate(dev_labels, predictions_tfidf_dev_gb)
gb_tfidf_f1 = f1_score(dev_labels, predictions_tfidf_dev_gb, average='macro')

#BernoulliNB on TFIDF
bnb_tfidf_acc = accurate(dev_labels, predictions_tfidf_dev_bnb)
bnb_tfidf_f1 = f1_score(dev_labels, predictions_tfidf_dev_bnb, average='macro')

#MultinomialNB on TFIDF
mb_tfidf_acc = accurate(dev_labels, predictions_tfidf_dev_mb)
mb_tfidf_f1 = f1_score(dev_labels, predictions_tfidf_dev_mb, average='macro')

#Logistic Regression on COUNT
lr_count_acc = accurate(dev_labels, predictions_count_dev_lr)
lr_count_f1 = f1_score(dev_labels, predictions_count_dev_lr, average='macro')

#Logistic Regression on TFIDF
lr_tfidf_acc = accurate(dev_labels, predictions_tfidf_dev_lr)
lr_tfidf_f1 = f1_score(dev_labels, predictions_tfidf_dev_lr, average='macro')

#SVM LINEAR on COUNT
svm_count_acc = accurate(dev_labels, predictions_count_dev_svm)
svm_count_f1 = f1_score(dev_labels, predictions_count_dev_svm, average='macro')

#SVM LINEAR on TFIDF
svm_tfidf_acc = accurate(dev_labels, predictions_tfidf_dev_svm)
svm_tfidf_f1 = f1_score(dev_labels, predictions_tfidf_dev_svm, average='macro')

#SVM SGD on COUNT
svm_count_SGD_acc = accurate(dev_labels, predictions_count_dev_SGD)
svm_count_SGD_f1 = f1_score(dev_labels, predictions_count_dev_SGD, average='macro')

#SVM SGD on TFIDF
svm_tfidf_SGD_acc = accurate(dev_labels, predictions_tfidf_dev_SGD)
svm_tfidf_SGD_f1 = f1_score(dev_labels, predictions_tfidf_dev_SGD, average='macro')

print(f"Zero R\t\t\t\t\t\tAccuracy: {round(zero_r_acc, 4)}\tMacro F1: {round(zero_r_f1, 4)}")
print(f"GaussianNB apply on 'count'\t\t\tAccuracy: {round(gb_count_acc, 4)}\tMacro F1: {round(gb_count_f1, 4)}")
print(f"GaussianNB apply on 'tfidf'\t\t\tAccuracy: {round(gb_tfidf_acc, 4)}\tMacro F1: {round(gb_tfidf_f1, 4)}")

print(f"BernoulliNB apply on 'count'\t\t\tAccuracy: {round(bnb_count_acc, 4)}\tMacro F1: {round(bnb_count_f1, 4)}")
print(f"BernoulliNB apply on 'tfidf'\t\t\tAccuracy: {round(bnb_tfidf_acc, 4)}\tMacro F1: {round(bnb_tfidf_f1, 4)}")

print(f"MultinomialNB apply on 'count'\t\t\tAccuracy: {round(mb_count_acc, 4)}\tMacro F1: {round (mb_count_f1, 4)}")
print(f"MultinomialNB apply on 'tfidf'\t\t\tAccuracy: {round(mb_tfidf_acc, 4)}\tMacro F1: {round(mb_tfidf_f1, 4)}")

print(f"Logistic Regression apply on 'count'\t\tAccuracy: {round(lr_count_acc, 4)}\tMacro F1: {round(lr_count_f1, 4)}")
print(f"Logistic Regression apply on 'tfidf'\t\tAccuracy: {round(lr_tfidf_acc, 4)}\tMacro F1: {round(lr_tfidf_f1, 4)}")

print(f"SVM LINEAR apply on 'count'\t\t\tAccuracy: {round(svm_count_acc, 4)}\tMacro F1: {round(svm_count_f1, 4)}")
print(f"SVM LINEAR apply on 'tfidf'\t\t\tAccuracy: {round(svm_tfidf_acc, 4)}\tMacro F1: {round(svm_tfidf_f1, 4)}")

print(f"SVM SGD apply on 'count'\t\t\tAccuracy: {round(svm_count_SGD_acc, 4)}\tMacro F1: {round(svm_count_SGD_f1, 4)}")
print(f"SVM SGD apply on 'tfidf'\t\t\tAccuracy: {round(svm_tfidf_SGD_acc, 4)}\t\tMacro F1: {round(svm_tfidf_SGD_f1, 4)}")


Zero R						Accuracy: 0.3743	Macro F1: 0.1362
GaussianNB apply on 'count'			Accuracy: 0.2249	Macro F1: 0.212
GaussianNB apply on 'tfidf'			Accuracy: 0.2309	Macro F1: 0.219
BernoulliNB apply on 'count'			Accuracy: 0.4565	Macro F1: 0.2949
BernoulliNB apply on 'tfidf'			Accuracy: 0.4565	Macro F1: 0.2949
MultinomialNB apply on 'count'			Accuracy: 0.4541	Macro F1: 0.2974
MultinomialNB apply on 'tfidf'			Accuracy: 0.4635	Macro F1: 0.2689
Logistic Regression apply on 'count'		Accuracy: 0.4577	Macro F1: 0.2837
Logistic Regression apply on 'tfidf'		Accuracy: 0.4431	Macro F1: 0.2517
SVM LINEAR apply on 'count'			Accuracy: 0.4593	Macro F1: 0.2772
SVM LINEAR apply on 'tfidf'			Accuracy: 0.4609	Macro F1: 0.2765
SVM SGD apply on 'count'			Accuracy: 0.4505	Macro F1: 0.278
SVM SGD apply on 'tfidf'			Accuracy: 0.433		Macro F1: 0.273


In [52]:

# synthetic classification dataset
from sklearn.datasets import make_classification
# define dataset
X, y = make_classification(n_samples=10000, n_features=20, n_informative=5, n_redundant=15, random_state=1)
# summarize the dataset
print(X.shape, y.shape)


(10000, 20) (10000,)


In [53]:
# split a dataset into train and test sets
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
# create dataset
X, y = make_classification(n_samples=10000, n_features=20, n_informative=5, n_redundant=15, random_state=1)
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
# summarize the shape of the train and test sets
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(7000, 20) (3000, 20) (7000,) (3000,)
